### ISSUE TITLE
HDB Plugin not working on Firefox

### ISSUE THREAD

**Issue by 0x2bad** [galac-tech/HE-hacked-database-helper#2]
As the title says, the script is currently not working with Firefox.

**Comment by jmerle** [comment]
#3 Added temporary fix for Greasemonkey on Firefox

The following lines are not working correctly on Firefox:

``` javascript
if (document.getElementsByClassName("link active")[0].innerText == "IP List\n") {
    injectTab();
    injectSettingsDiv();
}
```

The `if` is not succesful, even not when in the Hacked Database.

**Comment by ghost** [comment]
I've just fixed it. You guys were trying to make reference to a content that sometimes may not be available until the page is completely loaded. I just put this snippet (and others) into the callback function that is called when $(document).ready event is fired. Check my pull request out.

**Comment by galac-tech** [comment]
@perfilrobo where?

**Comment by ghost** [comment]
@galac-tech sorry.
Where, what?
